import { MAP_IDS } from '../sim/map.js';
const PROTOCOL=7;const PREFIX='animalfighter-v3-';
const validPlayers=p=>Array.isArray(p)&&p.length<=4&&p.every(a=>a&&Number.isInteger(a.id)&&a.id>=0&&a.id<4&&Number.isInteger(a.type)&&a.type>=0&&a.type<5&&typeof a.name==='string'&&a.name.length<=32);
const validState=s=>s&&typeof s==='object'&&Number.isInteger(s.seq)&&Number.isFinite(s.time)&&validPlayers(s.actors)&&s.actors.every(a=>Number.isFinite(a.x)&&Number.isFinite(a.y)&&Number.isFinite(a.hp))&&['props','limbs','bullets','effects','fires','events'].every(k=>Array.isArray(s[k])&&s[k].length<=1000)&&(s.map===undefined||MAP_IDS.includes(s.map))&&s.hazards&&typeof s.hazards==='object'&&Array.isArray(s.hazards.lamps)&&(s.hazards.map==='castle'||Array.isArray(s.hazards.cable));
const safeName=value=>String(value||'Visitante').replace(/[<>\x00-\x1f]/g,'').trim().slice(0,18)||'Visitante';
export class Multiplayer {
 constructor(onEvent){this.onEvent=onEvent;this.bots=3;this.map='depot';this.peer=null;this.connections=new Map();this.players=[];this.host=false;this.localId=0;this.code='';this.status='offline';this.started=false;this.closed=false;this.timer=null;this.lastSeen=new Map();this.lastSeq=-1;this.generation=0;}
 emit(type,data={}){this.onEvent({type,...data});}
 async create(name,type){this.close();this.closed=false;const gen=++this.generation;this.host=true;this.localId=0;this.players=[{id:0,name:safeName(name),type,bot:false}];const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';const nums=crypto.getRandomValues(new Uint8Array(6));this.code=Array.from(nums,x=>alphabet[x%alphabet.length]).join('');this.status='connecting';this.emit('status',{message:'Abrindo uma sala…'});return new Promise((resolve,reject)=>{let settled=false;const fail=error=>{if(settled||gen!==this.generation)return;settled=true;clearTimeout(this.timer);this.close();this.status='error';this.emit('error',{message:error});reject(new Error(error));};this.peer=new Peer(PREFIX+this.code,{secure:true,debug:0});this.timer=setTimeout(()=>fail('O servidor de salas não respondeu. Tente novamente.'),18000);this.peer.on('open',()=>{if(gen!==this.generation)return;clearTimeout(this.timer);settled=true;this.status='lobby';this.bindHost();this.emit('lobby',{code:this.code,players:this.players,host:true});resolve(this.code);});this.peer.on('error',e=>{const message=this.errorMessage(e);if(!settled)fail(message);else this.emit('error',{message});});this.peer.on('disconnected',()=>{if(!this.closed)this.emit('status',{message:'Servidor de salas desconectado. A partida atual pode continuar.'});});});}
 bindHost(){const generation=this.generation;this.peer.on('connection',conn=>{if(this.closed||generation!==this.generation){conn.close();return;}if(this.connections.size>=3||this.started||conn.metadata?.protocol!==PROTOCOL){conn.on('open',()=>{conn.send({type:'rejected',message:this.started?'Esta partida já começou. Aguarde a próxima.':'Sala cheia ou versão incompatível.'});setTimeout(()=>conn.close(),400)});return;}let id=[1,2,3].find(i=>!this.connections.has(i));if(id===undefined){conn.close();return;}this.connections.set(id,conn);const handshake=setTimeout(()=>{if(!conn.open){remove();conn.close();}},14000);conn.on('open',()=>{clearTimeout(handshake);if(this.closed||generation!==this.generation){conn.close();return;}if(this.started){conn.close();return;}const p={id,name:safeName(conn.metadata?.name),type:Number.isInteger(conn.metadata?.character)?Math.max(0,Math.min(4,conn.metadata.character)):0,bot:false};this.players.push(p);this.lastSeen.set(id,performance.now());conn.send({type:'welcome',protocol:PROTOCOL,id,code:this.code});this.broadcastLobby();});conn.on('data',data=>{if(this.closed||generation!==this.generation||!data||typeof data!=='object')return;if(data.type==='input'&&this.started&&data.input&&typeof data.input==='object'){this.lastSeen.set(id,performance.now());const input={};for(const k of ['left','right','jump','down','attack','power','grab','dodge','drop','detonate','bats'])input[k]=data.input?.[k]===true;input.aimX=Number.isFinite(data.input?.aimX)?Math.max(-100,Math.min(1060,data.input.aimX)):null;input.aimY=Number.isFinite(data.input?.aimY)?Math.max(-100,Math.min(650,data.input.aimY)):null;this.emit('input',{id,input});}else if(data.type==='ping')conn.send({type:'pong',at:data.at});else if(data.type==='pick'&&!this.started&&Number.isInteger(data.character)){const p=this.players.find(p=>p.id===id);if(p){p.type=Math.max(0,Math.min(4,data.character));this.broadcastLobby();}}});const remove=()=>{clearTimeout(handshake);if(this.connections.get(id)!==conn)return;this.connections.delete(id);this.players=this.players.filter(p=>p.id!==id);this.lastSeen.delete(id);if(!this.closed&&generation===this.generation){this.emit('left',{id});this.broadcastLobby();}};conn.on('close',remove);conn.on('error',remove);});}
 async join(code,name,type){this.close();this.closed=false;const gen=++this.generation;code=String(code).trim().toUpperCase();if(!/^[A-Z2-9]{6}$/.test(code))throw new Error('Digite o código de 6 letras e números da sala.');this.code=code;this.host=false;this.status='connecting';this.emit('status',{message:'Procurando a sala…'});return new Promise((resolve,reject)=>{let settled=false;const fail=message=>{if(settled||gen!==this.generation)return;settled=true;clearTimeout(this.timer);this.close();this.status='error';this.emit('error',{message});reject(new Error(message));};this.peer=new Peer({secure:true,debug:0});this.timer=setTimeout(()=>fail('Não foi possível conectar. Confira o código e se o anfitrião está com a sala aberta.'),22000);this.peer.on('open',()=>{if(gen!==this.generation)return;const conn=this.peer.connect(PREFIX+code,{reliable:true,serialization:'binary',metadata:{protocol:PROTOCOL,name:safeName(name),character:type}});this.connections.set(0,conn);conn.on('data',data=>{if(this.closed||gen!==this.generation||!data||typeof data!=='object')return;if(data.type==='rejected'){fail(data.message);conn.close();return;}if(data.type==='welcome'){if(settled)return;if(!Number.isInteger(data.id)||data.id<1||data.id>3||data.protocol!==PROTOCOL){fail('Versão incompatível. Atualize o jogo.');return;}settled=true;clearTimeout(this.timer);this.localId=data.id;this.status='lobby';resolve(data.id);}else if(data.type==='lobby'&&settled&&validPlayers(data.players)){this.players=data.players;if(Number.isInteger(data.bots))this.bots=Math.max(0,Math.min(3,data.bots));if(MAP_IDS.includes(data.map))this.map=data.map;this.emit('lobby',{code:this.code,players:this.players,host:false});}else if(data.type==='start'&&settled&&validPlayers(data.players)){this.started=true;this.status='playing';this.lastSeq=-1;this.emit('start',{players:data.players,localId:this.localId,map:MAP_IDS.includes(data.map)?data.map:'depot'});}else if(data.type==='state'&&settled&&this.started&&validState(data.state)){if(data.state.seq>this.lastSeq){this.lastSeq=data.state.seq;this.emit('state',{state:data.state});}}else if(data.type==='end'&&settled){this.started=false;this.status='lobby';this.emit('end',{message:data.message||'O anfitrião voltou para a sala.'});}else if(data.type==='pong'){this.emit('latency',{ms:Math.round(performance.now()-data.at)});}});conn.on('close',()=>{if(this.closed)return;if(!settled)fail('A sala foi fechada.');this.status='offline';this.emit('disconnected',{message:'O anfitrião saiu. A sala foi encerrada.'});});conn.on('error',()=>fail('A conexão com a sala falhou. Tente novamente.'));});this.peer.on('error',e=>{if(!settled)fail(this.errorMessage(e));else this.emit('error',{message:this.errorMessage(e)});});});}
 errorMessage(e){return e.type==='peer-unavailable'?'Sala não encontrada. Confira o código.':e.type==='unavailable-id'?'Esse código já está ocupado. Crie outra sala.':e.type==='browser-incompatible'?'Este navegador não oferece WebRTC. Use Chrome, Edge, Firefox ou Safari atualizado.':'Não foi possível conectar ao servidor de salas. Tente novamente.';}
 broadcast(data){for(const conn of this.connections.values())if(conn.open){try{conn.send(data);}catch{ /* close/error events update room state */ }}}
 broadcastLobby(){this.broadcast({type:'lobby',players:this.players,bots:this.bots,map:this.map});this.emit('lobby',{code:this.code,players:this.players,host:true});}
 start(players){if(!this.host||!this.peer?.open)throw new Error('A sala ainda não está pronta.');this.started=true;this.status='playing';this.broadcast({type:'start',players,map:this.map});}
 sendState(state){if(!this.host||!this.started)return;for(const conn of this.connections.values())if(conn.open&&(conn.dataChannel?.bufferedAmount||0)<60000&&conn.bufferSize<3)conn.send({type:'state',state});}
 sendInput(input){const conn=this.connections.get(0);if(conn?.open&&this.started&&(conn.dataChannel?.bufferedAmount||0)<20000)conn.send({type:'input',input});}
 clearStaleInputs(){if(this.host&&this.started){const now=performance.now();for(const [id,last] of this.lastSeen)if(now-last>500)this.emit('input',{id,input:{}});}}
 // How many bots fill the free places when the host starts (0 to 3).
 setBots(n){this.bots=Math.max(0,Math.min(3,n|0));if(this.host&&this.peer?.open)this.broadcast({type:'lobby',players:this.players,bots:this.bots,map:this.map});}
 // The arena the host picked (sim/map.js MAP_IDS).
 setMap(id){if(!MAP_IDS.includes(id))return;this.map=id;if(this.host&&this.peer?.open)this.broadcast({type:'lobby',players:this.players,bots:this.bots,map:this.map});}
 // Changing fighter in the lobby: the host updates its own entry, a guest asks the host.
 pick(type){type=Math.max(0,Math.min(4,type|0));if(this.started)return;if(this.host){const p=this.players.find(p=>p.id===0);if(p){p.type=type;if(this.peer?.open)this.broadcastLobby();}return;}const conn=this.connections.get(0);if(conn?.open){try{conn.send({type:'pick',character:type});}catch{}}}
 ping(){if(!this.host){const conn=this.connections.get(0);if(conn?.open)conn.send({type:'ping',at:performance.now()});}}
 end(){if(this.host)this.broadcast({type:'end'});this.started=false;this.status='lobby';}
 close(){this.closed=true;this.generation++;clearTimeout(this.timer);for(const conn of this.connections.values())conn.close();this.connections.clear();this.peer?.destroy();this.peer=null;this.players=[];this.status='offline';this.started=false;this.lastSeen.clear();this.lastSeq=-1;}
}
